version: "3.9"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    hostname: "mssql"
    restart: always
    ports: 
        - 1433:1433
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=75e5adc3-90ae-4e6c-aa5d-f45000462cc7
